apiVersion: apps/v1
kind: Deployment
metadata:
  name: certman-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: certman-operator
  template:
    metadata:
      labels:
        name: certman-operator
    spec:
      serviceAccountName: certman-operator
      containers:
        - name: certman-operator
          image: quay.io/ntaneja/certman-operator:adding_metrics_for_prometheus_alerts
          command:
          - certman-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "certman-operator"
